### ISSUE TITLE
Issue in in stalling the project

### ISSUE THREAD

**Issue by krunalee-rane182** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#1]
Issue in installing the project, please help

Error-
Could not find module "@angular-devkit/build-angular" from "E:\\krunalee\\angular6 and firebase\\onlinestore\\Online-Shop-eCommerce-App-Angular-6-Firebase".
Error: Could not find module "@angular-devkit/build-angular" from "E:\\krunalee\\angular6 and firebase\\onlinestore\\Online-Shop-eCommerce-App-Angular-6-Firebase".
    at Object.resolve (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:132:40)
    at Observable._trySubscribe (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:29:22)
    at DoOperator.call (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (C:\Users\dell\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:72:14)

**Comment by AmitXShukla** [comment]
I am sure you have issues with your ng -installation.
Can you please run 
node -v
npm -v
ng --version

and make sure you are inside your project directory (folder where your package.json file is) and then run 
ng serve

Perhaps, I can be more helpful if you can can send me following in email (amit@elishconsulting.com)
screen shots of your project folders, package.json and terminal window showing error
