### ISSUE TITLE
issue while running 

### ISSUE THREAD

**Issue by Y0geshsharma** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#3]
[error] Error: Error: ENOENT: no such file or directory, lstat '/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/tsconfig.app.json'
    at Object.lstatSync (fs.js:845:3)
    at NodeJSFileSystem.lstat (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.js:38:72)
    at calcProjectFileAndBasePath (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular/compiler-cli/src/perform_compile.js:114:31)
    at Object.readConfiguration (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular/compiler-cli/src/perform_compile.js:132:22)
    at Object.readTsconfig (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/read-tsconfig.js:25:29)
    at generateWebpackConfig (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:96:12)
    at Object.generateBrowserWebpackConfigFromContext (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:107:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

    at Object.readTsconfig (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/read-tsconfig.js:27:15)
    at generateWebpackConfig (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:96:12)
    at Object.generateBrowserWebpackConfigFromContext (/home/work/ecommerse/Online-Shop-eCommerce-App-Angular-6-Firebase/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:107:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

my angular CLI version:8.2.2

**Comment by Thomas-Ahn** [comment]
check your angular.conf and make a correct location of tsconfig.app.json, "tsConfig": "src/tsconfig.app.json".
