### ISSUE TITLE
shows error while doing ng serve

### ISSUE THREAD

**Issue by keyurpanchal** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#6]
hi sir, i had created project named msos1. now i deleted all files form there just  the node_modules and e2e files is in msos1 project folder, and then puted all the files that you provided in the master branch. but when i do ng serve it gets erorrs and at 4200 output only ' Cannot GET /' .please help me out to run this project . this is very important for me !

**Comment by AmitXShukla** [comment]
can you please share terminal window and browser console, errors.

**Comment by keyurpanchal** [comment]
ERROR in node_modules/rxjs/Observable.d.ts:1:15 - error TS2307: Cannot find module 'rxjs-compat/Observable'.

1 export * from 'rxjs-compat/Observable';
                ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/Rx.d.ts:1:15 - error TS2307: Cannot find module 'rxjs-compat'.

1 export * from 'rxjs-compat';
                ~~~~~~~~~~~~~
src/app/admin/admin.component.ts:4:28 - error TS2307: Cannot find module '@angular/cdk/collections'.

4 import { DataSource } from '@angular/cdk/collections';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/admin.component.ts:5:59 - error TS2307: Cannot find module '@angular/material'.

5 import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
                                                            ~~~~~~~~~~~~~~~~~~~
src/app/admin/admin.login.component.ts:4:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

4 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/admin/setproduct.component.ts:3:28 - error TS2307: Cannot find module '@angular/cdk/collections'.

3 import { DataSource } from '@angular/cdk/collections';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/setproduct.component.ts:4:59 - error TS2307: Cannot find module '@angular/material'.

4 import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
                                                            ~~~~~~~~~~~~~~~~~~~
src/app/admin/setproduct.component.ts:6:36 - error TS2307: Cannot find module '@angular/fire/storage'.

6 import { AngularFireStorage } from '@angular/fire/storage';
                                     ~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:2:30 - error TS2307: Cannot find module '@angular/cdk/layout'.

2 import { LayoutModule } from '@angular/cdk/layout';
                               ~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:16:35 - error TS2307: Cannot find module '@angular/fire'.

16 import { AngularFireModule } from '@angular/fire';
                                     ~~~~~~~~~~~~~~~
src/app/app.module.ts:17:40 - error TS2307: Cannot find module '@angular/fire/firestore'.

17 import { AngularFirestoreModule } from '@angular/fire/firestore';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:18:42 - error TS2307: Cannot find module '@angular/fire/storage'.

18 import { AngularFireStorageModule } from '@angular/fire/storage';
                                            ~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:19:39 - error TS2307: Cannot find module '@angular/fire/auth'.

19 import { AngularFireAuthModule } from '@angular/fire/auth';
                                         ~~~~~~~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:3:33 - error TS2307: Cannot find module '@angular/fire/auth'.

3 import { AngularFireAuth } from '@angular/fire/auth';
                                  ~~~~~~~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:5:27 - error TS2307: Cannot find module 'firebase/app'.

5 import * as firebase from 'firebase/app';
                            ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:7:22 - error TS2307: Cannot find module 'firebase/app'.

7 import { auth } from 'firebase/app';
                       ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:10:27 - error TS2307: Cannot find module 'firebase/app'.

10 import { firestore } from 'firebase/app';
                             ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:13:88 - error TS2307: Cannot find module '@angular/fire/firestore'.

13 import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/settings/settings.component.ts:5:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

5 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/shared/dropzone/fileupload.component.ts:2:59 - error TS2307: Cannot find module '@angular/fire/storage'.

2 import { AngularFireStorage, AngularFireUploadTask } from '@angular/fire/storage';
                                                            ~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/dropzone/fileupload.component.ts:3:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

3 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/shared/elish.material.module.ts:32:16 - error TS2307: Cannot find module '@angular/material'.

32         } from '@angular/material';
                  ~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:37:31 - error TS2307: Cannot find module '@angular/material'.

37 import {MatIconRegistry} from '@angular/material';
                                 ~~~~~~~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:4:33 - error TS2307: Cannot find module '@angular/fire/auth'.

4 import { AngularFireAuth } from '@angular/fire/auth';
                                  ~~~~~~~~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:6:27 - error TS2307: Cannot find module 'firebase/app'.

6 import { firestore } from 'firebase/app';
                            ~~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:9:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Rx"' has no exported member 'Observable'.

9 import { Observable } from "rxjs/Rx";
           ~~~~~~~~~~
src/app/shop/shopping.component.ts:3:28 - error TS2307: Cannot find module '@angular/cdk/collections'.

3 import { DataSource } from '@angular/cdk/collections';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:4:59 - error TS2307: Cannot find module '@angular/material'.

4 import { MatPaginator, MatSort, MatTableDataSource } from '@angular/material';
                                                            ~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:6:36 - error TS2307: Cannot find module '@angular/fire/storage'.

6 import { AngularFireStorage } from '@angular/fire/storage';
                                     ~~~~~~~~~~~~~~~~~~~~~~~

ERROR in ./src/assets/css/styles.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/css/styles.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '@angular/material/prebuilt-themes/indigo-pink.css'
  in [
    D:\msos1\src\assets\css
  ]
    at D:\msos1\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async Promise.all (index 0)
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by keyurpanchal** [comment]
i just created that msos1 project and puted files you provided haven't edited anything !!

**Comment by AmitXShukla** [comment]
Got it, Thanks for checking.
I see issue now, these are all related to new Angular version.
I’ll have to update this repo.
I’ll lease expect an update early next week.

**Comment by keyurpanchal** [comment]
ok sir ! but i have little urgency is there any way i can start this project ? checked version where there is error in four packages.[here is link](https://lh3.googleusercontent.com/Ec-Fob0YnNjrAnDiIjVkJxHjTrBVHuzMmK2ajIF1o98dI40Zg-lJI8KrKuGZOcwyihGCjbqHYsPSKCHrt5ioB0fIqNCQ2bdGn1huqNRaGsyTwEQ9pyqBYrusBHzE5AZlO1ug3UfhOHmU8dQbo9NW0BXFXQlCaICXenWmA0dU_n-O49Z7du4ll_BmfX_krTSyXfK4L2jAnVddFuNvE2FHEY_UK-vXkP0vno9Eb0sqxSB7_E2WA8deicGw6lcd4q9bMiS8Q2OKXRxKBmUDkHb4zgkTU7YFwcW7B-f82VqjV5y4w05NoulGifyHxWVSXvgyOUCsN1sP39N9v8hMJT8hQfgL02oesdmNsoxxcNIrIXBSgFtyLho7VkmwVF0NZtqrWPyWNSrQHcUf4PqIt6q4ccpDeaCHawGE4x70h1fplOvmkd2SXVEi232CY1DPKiQzr0wxD6luEqKmZlKzPm26GuiGNWBnPWevkbLMYWA2rrc-hdry5w5LOHH-5c0cJkD9MoQV59rlZpYmFr1T2qcOjrvZGJo3RvFKTTX-NgwC0lRga8eU5B2mrB55YjQG1NUTSUKb_54YnCShWy1Sm9ybSHZ6xk-AoH57Joj4IeBA8TFUt7HF9hSVvgc9l5wQhPt34u7cQXBgNq-XDDHZ9d4bCBcQ3h32oeybgU7Rx6OQSbjzybXT-XyQfmZQFQwz=w493-h657-no)

**Comment by AmitXShukla** [comment]
What you can do is, download my code as is,
Go to package.json 
Remove all ~ and ^ in front of npm packages
And do a npm install

This will force your project to download last version of packages and not latest packages.

Let me know if this doesn’t work, I will try to fix this tomorrow.

**Comment by keyurpanchal** [comment]
Ok i will do it ASAP ..thanks a lot , sir .

**Comment by AmitXShukla** [comment]
I uploaded a newer version, I am not sure if there are still some new errors, can you please download a fresh copy and install.

**Comment by keyurpanchal** [comment]
Ok sir 👍 thank you

**Comment by keyurpanchal** [comment]
ERROR in src/app/shared/elish.material.module.ts:5:31 - error TS2307: Cannot find module '@angular/material/button'.

5 import {MatButtonModule} from '@angular/material/button';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:6:33 - error TS2307: Cannot find module '@angular/material/checkbox'.

6 import {MatCheckboxModule} from '@angular/material/checkbox';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:7:34 - error TS2307: Cannot find module '@angular/material/form-field'.

7 import {MatFormFieldModule} from '@angular/material/form-field';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:8:31 - error TS2307: Cannot find module '@angular/material/dialog'.

8 import {MatDialogModule} from '@angular/material/dialog';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:9:29 - error TS2307: Cannot find module '@angular/material/tabs'.

9 import {MatTabsModule} from '@angular/material/tabs';
                              ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:10:40 - error TS2307: Cannot find module '@angular/material/progress-spinner'.

10 import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:11:29 - error TS2307: Cannot find module '@angular/material/menu'.

11 import {MatMenuModule} from '@angular/material/menu';
                               ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:12:30 - error TS2307: Cannot find module '@angular/material/input'.

12 import {MatInputModule} from '@angular/material/input';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:13:31 - error TS2307: Cannot find module '@angular/material/select'.

13 import {MatSelectModule} from '@angular/material/select';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:14:32 - error TS2307: Cannot find module '@angular/material/toolbar'.

14 import {MatToolbarModule} from '@angular/material/toolbar';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:15:29 - error TS2307: Cannot find module '@angular/material/card'.

15 import {MatCardModule} from '@angular/material/card';
                               ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:16:30 - error TS2307: Cannot find module '@angular/material/chips'.

16 import {MatChipsModule} from '@angular/material/chips';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:17:29 - error TS2307: Cannot find module '@angular/material/list'.

17 import {MatListModule} from '@angular/material/list';
                               ~~~~~~~~~~~~~~~~~~~~~~~~39m0m
src/app/shared/elish.material.module.ts:18:32 - error TS2307: Cannot find module '@angular/material/tooltip'.

18 import {MatTooltipModule} from '@angular/material/tooltip';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:19:35 - error TS2307: Cannot find module '@angular/material/datepicker'.

19 import {MatDatepickerModule} from '@angular/material/datepicker';
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:20:30 - error TS2307: Cannot find module '@angular/material/table'.

20 import {MatTableModule} from '@angular/material/table';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:21:34 - error TS2307: Cannot find module '@angular/material/paginator'.

21 import {MatPaginatorModule} from '@angular/material/paginator';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:22:29 - error TS2307: Cannot find module '@angular/material/sort'.

22 import {MatSortModule} from '@angular/material/sort';
                               ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:23:36 - error TS2307: Cannot find module '@angular/material/progress-bar'.

23 import {MatProgressBarModule} from '@angular/material/progress-bar';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:24:33 - error TS2307: Cannot find module '@angular/material/snack-bar'.

24 import {MatSnackBarModule} from '@angular/material/snack-bar';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:25:32 - error TS2307: Cannot find module '@angular/material/stepper'.

25 import {MatStepperModule} from '@angular/material/stepper';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:26:33 - error TS2307: Cannot find module '@angular/material/grid-list'.

26 import {MatGridListModule} from '@angular/material/grid-list';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:27:34 - error TS2307: Cannot find module '@angular/material/expansion'.

27 import {MatExpansionModule} from '@angular/material/expansion';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:28:30 - error TS2307: Cannot find module '@angular/material/radio'.

28 import {MatRadioModule} from '@angular/material/radio';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:29:30 - error TS2307: Cannot find module '@angular/material/badge'.

29 import {MatBadgeModule} from '@angular/material/badge';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:36:31 - error TS2307: Cannot find module '@angular/material/icon'.

36 import {MatIconRegistry} from '@angular/material/icon';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/elish.material.module.ts:37:29 - error TS2307: Cannot find module '@angular/material/icon'.

37 import {MatIconModule} from '@angular/material/icon';
                               ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:3:33 - error TS2307: Cannot find module '@angular/fire/auth'.

3 import { AngularFireAuth } from '@angular/fire/auth';
                                  ~~~~~~~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:5:27 - error TS2307: Cannot find module 'firebase/app'.

5 import * as firebase from 'firebase/app';
                            ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:7:22 - error TS2307: Cannot find module 'firebase/app'.

7 import { auth } from 'firebase/app';
                       ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:10:27 - error TS2307: Cannot find module 'firebase/app'.

10 import { firestore } from 'firebase/app';
                             ~~~~~~~~~~~~~~
src/app/services/firebase.service.ts:13:88 - error TS2307: Cannot find module '@angular/fire/firestore'.

13 import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/Rx.d.ts:1:15 - error TS2307: Cannot find module 'rxjs-compat'.

1 export * from 'rxjs-compat';
                ~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:4:33 - error TS2307: Cannot find module '@angular/fire/auth'.

4 import { AngularFireAuth } from '@angular/fire/auth';
                                  ~~~~~~~~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:6:27 - error TS2307: Cannot find module 'firebase/app'.

6 import { firestore } from 'firebase/app';
                            ~~~~~~~~~~~~~~
src/app/shared/login/login.component.ts:9:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Rx"' has no exported member 'Observable'.

9 import { Observable } from "rxjs/Rx";
           ~~~~~~~~~~
node_modules/rxjs/Observable.d.ts:1:15 - error TS2307: Cannot find module 'rxjs-compat/Observable'.

1 export * from 'rxjs-compat/Observable';
                ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/settings/settings.component.ts:5:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

5 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/admin/admin.component.ts:5:52 - error TS2307: Cannot find module '@angular/material/table'.

5 import { MatTableModule, MatTableDataSource } from '@angular/material/table';
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/admin.component.ts:6:30 - error TS2307: Cannot find module '@angular/material/paginator'.

6 import { MatPaginator } from '@angular/material/paginator';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/admin.component.ts:7:25 - error TS2307: Cannot find module '@angular/material/sort'.

7 import { MatSort } from '@angular/material/sort';
                          ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/admin.login.component.ts:4:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

4 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/admin/setproduct.component.ts:4:52 - error TS2307: Cannot find module '@angular/material/table'.

4 import { MatTableModule, MatTableDataSource } from '@angular/material/table';
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/setproduct.component.ts:5:30 - error TS2307: Cannot find module '@angular/material/paginator'.

5 import { MatPaginator } from '@angular/material/paginator';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/setproduct.component.ts:6:25 - error TS2307: Cannot find module '@angular/material/sort'.

6 import { MatSort } from '@angular/material/sort';
                          ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/admin/setproduct.component.ts:8:36 - error TS2307: Cannot find module '@angular/fire/storage'.

8 import { AngularFireStorage } from '@angular/fire/storage';
                                     ~~~~~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:4:52 - error TS2307: Cannot find module '@angular/material/table'.

4 import { MatTableModule, MatTableDataSource } from '@angular/material/table';
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:5:30 - error TS2307: Cannot find module '@angular/material/paginator'.

5 import { MatPaginator } from '@angular/material/paginator';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:6:25 - error TS2307: Cannot find module '@angular/material/sort'.

6 import { MatSort } from '@angular/material/sort';
                          ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/shop/shopping.component.ts:8:36 - error TS2307: Cannot find module '@angular/fire/storage'.

8 import { AngularFireStorage } from '@angular/fire/storage';
                                     ~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/dropzone/fileupload.component.ts:2:59 - error TS2307: Cannot find module '@angular/fire/storage'.

2 import { AngularFireStorage, AngularFireUploadTask } from '@angular/fire/storage';
                                                            ~~~~~~~~~~~~~~~~~~~~~~~
src/app/shared/dropzone/fileupload.component.ts:3:10 - error TS2305: Module '"D:/msos1/node_modules/rxjs/Observable"' has no exported member 'Observable'.

3 import { Observable } from 'rxjs/Observable';
           ~~~~~~~~~~
src/app/app.module.ts:3:30 - error TS2307: Cannot find module '@angular/cdk/layout'.

3 import { LayoutModule } from '@angular/cdk/layout';
                               ~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:39mm17:35 - error TS2307: Cannot find module '@angular/fire'.

17 import { AngularFireModule } from '@angular/fire';
                                     ~~~~~~~~~~~~~~~
src/app/app.module.ts:18:40 - error TS2307: Cannot find module '@angular/fire/firestore'.

18 import { AngularFirestoreModule } from '@angular/fire/firestore';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:19:42 - error TS2307: Cannot find module '@angular/fire/storage'.

19 import { AngularFireStorageModule } from '@angular/fire/storage';
                                            ~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:20:39 - error TS2307: Cannot find module '@angular/fire/auth'.

20 import { AngularFireAuthModule } from '@angular/fire/auth';
                                         ~~~~~~~~~~~~~~~~~~~~

ERROR in ./src/assets/css/styles.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/css/styles.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '@angular/material/prebuilt-themes/indigo-pink.css'
  in [
    D:\msos1\src\assets\css
  ]
    at D:\msos1\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async Promise.all (index 0)
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

replaced src and other folders and deleted all other ..did't worked :(

**Comment by keyurpanchal** [comment]
in app.module shows [this error ](https://lh3.googleusercontent.com/hGdWzWAT24vfRfwUqEmwyvM7HupQEYuP1118LyutFcUg8t0Kn_1Lu2SuKkraFVlyDkdwRIoKGmrPwFWljRNeGq9iRfEuA0T0haHEr5x-__McxZIfdBkOvnadr04JJBhPdfmIhKhQqOFZ7Q82TQjb2OWnmKDGUTtivNT2M7Gjh8xchO1DicLUDfxq9oJFkQ3FqE2WsuhHYB_z3t428icyO6UadG1NudoQP6fZ-ksYm7OVFPqrMeVmgJg5LyCFgUj5C2M0YLrMobvAgxKYaDh8eqo4FrRD9LoIW4uaqjjgab9AwBFQd6U6Z_5E3GFb4BRtTccTxp-u4FcdZK8F44m1tV5rcf4QMeA2zJ6Dhkc--OjFJYHDwZhNENbfYOAP-mcuUT8m7LdTG1XvR7PtpRIoGyu_mJwxi7fGM_4bADzqzE0CHVmqUon5LP5QmNzVcFwpDgHpa1HuqxPOPCq8aKjkHWxlxuiyq-u8EFRa8B-Zy3ooVyqPvsNKCHAl7s6SCbmE9Yt6eGwzqIawtneVaIDRm0jVZCAf1HIOtTBAhLeot1-XCRBDdJfyCAD4EPAoguV5odVeT58yeTyr4quE9IIdLYYR6FimFV2IVV3Xeq4L-H42GXeT8XgFPrZPh3vrgR55bVfrxWWmzoGUsR4EgkqT6BVkAzObNWFU4rQvZuG2gZ4zTGGl7m0_J2UTIatS=w456-h608-no)

**Comment by AmitXShukla** [comment]
Please delete your node_modules folder, update package.json and do a complete npm install again

**Comment by AmitXShukla** [comment]
I assume it worked for you, I will re-open this repository and upgrade. Also please expect a new installation video in near future. You will find links at readme.md file.
